
private key block -----BEGIN PRIVATE KEY----- L8qq9PZyRg6ieKGEKhZolGC0vJWLw8iEJ88DRdyOg
RSA private key	-----BEGIN RSA PRIVATE KEY----- GRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
SSH (DSA) private key	-----BEGIN DSA PRIVATE KEY----- id%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9U
SSH (EC) private key -----BEGIN EC PRIVATE KEY----- query=from%3Atwitterdev
PGP private key block -----BEGIN PGP PRIVATE KEY BLOCK----- UifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
AKIAIOSFODNN7EXAMPLE Amazon AWS Access Key ID
Amazon MWS Auth Token    amzn\\.mws\\.APJ6JRA9NG5V4
AKIAI44QH8DHBEXAMPLE AWS API Key
